name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  # repository_dispatch allows you too rest api requst triggers workflow
  # schedule  Workflow is scheduled
  # workflow_call Can be caller by other workflow
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo First action
          echo Second action
